### PR TITLE
If the user is not found, at least return the ID.

### PR DESCRIPTION
**Pull request by Burkes**
https://i.imgur.com/sw23Zpo.png

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Hm, I'd rather have it consistently return User objects. There's likely a bug somewhere that causes it to not have the user object available at that time. Is there a situation where this happens consistently?

**Comment by Burkes** [comment]
I would have to frequently deal with Ghost users, they can be intentionally made and controlled. Even the dj property on the advance event was undefined when one entered the booth. The plug front end code does a bulk request when an unknown ID enters the waitlist so they're at least visible in the room. Same reason guest count drops below 0.

Is there another way I can get the raw data of the waitlist update event instead? Cause an ID is better than undefined.

**Comment by goto-bus-stop** [comment]
Ahh, i see. In that case let's default to user objects with just the user ID, so they still support all the methods like other user objects. That way library users don't have to type-check every result manually. Should be something like `wrapUser(mp, { id: id })`.

**Comment by Burkes** [comment]
Ahh, good one. Just making sure, cause I'm not familiar with how this is made, but I'd need to get partial and the user model in the waitlist plugin?

Also, the only method that wouldn't work would be mention.

**Comment by goto-bus-stop** [comment]
You'd need to get the `wrapUser` function for use inside the `wrapWaitlist` function, and then pass on the `mp` variable that's available in `wrapWaitlist`. For reference, the historyEntry data model also calls the User model in that way: https://github.com/goto-bus-stop/miniplug/blob/84f986fdad777e99885cf3535c6cc10881d4d9fd/src/data/historyEntry.js#L14

**Comment by Burkes** [comment]
done :+1:

**Comment by goto-bus-stop** [comment]
I think we should use the `mp.user()` result if it's available, and use the `wrapUser` way only if it's not. Can you make that change? Looks good otherwise :tada:

**Comment by goto-bus-stop** [comment]
Sweet, thanks! :pray: I'm on mobile now so will release tomorrow.

**Pull request merged**
